### ISSUE TITLE
Please add latitude/longitude/language family to CLDF. 

### ISSUE THREAD

**Issue by SimonGreenhill** [numeralbank/channumerals#48]
These columns are currently empty, but this would make the CLDF self-contained.

**Comment by SimonGreenhill** [comment]
@Bibiko @chrzyki

**Comment by Bibiko** [comment]
since channumerals is an "intermediated"-repo (non-curated) I'd suggest to add these data to numeralbank/numerals repo

**Comment by xrotwang** [comment]
@Bibiko but we want this repo to be usable on its own as well - not just via `numeralbank/numerals`.

**Comment by SimonGreenhill** [comment]
btw -- can someone give me access to numeralbank/numerals? danke.

**Comment by chrzyki** [comment]
> btw -- can someone give me access to numeralbank/numerals? danke.

Done

**Comment by Bibiko** [comment]
Ok - I'll add this information

**Comment by SimonGreenhill** [comment]
thnks!
